import type { FixtureRecord } from './types'

export const FIXTURES: Record<FixtureRecord['id'], FixtureRecord> = {
  SYN_CLEAN_LODGING: {
    id: 'SYN_CLEAN_LODGING',
    travelerPersona: 'Synthetic Traveler A',
    fakeVoucherSeed: 'SYN-VCH-0001',
    tripPurpose: 'Training visit',
    dateRange: '2026-05-01..2026-05-03',
    category: 'lodging',
    amountSyntheticCredits: 320,
    fakeAuthorizedAmount: 320,
    fakeReceiptPresent: true,
    amountMatchesAuthorization: true,
    explanation: 'Synthetic stay with standard lodging details for the demo flow.',
    expectedDetermination: 'accepted',
    expectedRuleIds: ['DEFAULT_ACCEPT'],
    transcript: [
      'Synthetic Traveler A',
      'Training visit',
      '2026-05-01..2026-05-03',
      'lodging',
      '320',
      'yes',
      'yes',
      'Synthetic stay with standard lodging details for the demo flow.',
    ],
  },
  SYN_MISSING_RECEIPT: {
    id: 'SYN_MISSING_RECEIPT',
    travelerPersona: 'Synthetic Traveler B',
    fakeVoucherSeed: 'SYN-VCH-0002',
    tripPurpose: 'Site walkthrough',
    dateRange: '2026-05-04..2026-05-05',
    category: 'lodging',
    amountSyntheticCredits: 280,
    fakeAuthorizedAmount: 280,
    fakeReceiptPresent: false,
    amountMatchesAuthorization: true,
    explanation: 'Synthetic overnight stay with a missing fake receipt.',
    expectedDetermination: 'request_more_info',
    expectedRuleIds: ['LODGING_NEEDS_RECEIPT'],
    transcript: [
      'Synthetic Traveler B',
      'Site walkthrough',
      '2026-05-04..2026-05-05',
      'lodging',
      '280',
      'no',
      'yes',
      'Synthetic overnight stay with a missing fake receipt.',
    ],
  },
  SYN_AMOUNT_MISMATCH: {
    id: 'SYN_AMOUNT_MISMATCH',
    travelerPersona: 'Synthetic Traveler C',
    fakeVoucherSeed: 'SYN-VCH-0003',
    tripPurpose: 'Transit exchange',
    dateRange: '2026-05-06..2026-05-06',
    category: 'transit',
    amountSyntheticCredits: 640,
    fakeAuthorizedAmount: 500,
    fakeReceiptPresent: true,
    amountMatchesAuthorization: false,
    explanation: 'Synthetic transit line with a deliberate gap for rule coverage.',
    expectedDetermination: 'rejected',
    expectedRuleIds: ['AMOUNT_MISMATCH'],
    transcript: [
      'Synthetic Traveler C',
      'Transit exchange',
      '2026-05-06..2026-05-06',
      'transit',
      '640',
      'yes',
      'no',
      'Synthetic transit line with a deliberate gap for rule coverage.',
    ],
  },
  SYN_AMBIGUOUS_MISC: {
    id: 'SYN_AMBIGUOUS_MISC',
    travelerPersona: 'Synthetic Traveler D',
    fakeVoucherSeed: 'SYN-VCH-0004',
    tripPurpose: 'Demo support',
    dateRange: '2026-05-07..2026-05-08',
    category: 'misc',
    amountSyntheticCredits: 550,
    fakeAuthorizedAmount: 550,
    fakeReceiptPresent: true,
    amountMatchesAuthorization: true,
    explanation: 'Need help soon',
    expectedDetermination: 'escalated',
    expectedRuleIds: ['AMBIGUOUS_NEAR_THRESHOLD'],
    transcript: [
      'Synthetic Traveler D',
      'Demo support',
      '2026-05-07..2026-05-08',
      'misc',
      '550',
      'yes',
      'yes',
      'Need help soon',
    ],
  },
  SYN_TRANSIT_SMALL: {
    id: 'SYN_TRANSIT_SMALL',
    travelerPersona: 'Synthetic Traveler E',
    fakeVoucherSeed: 'SYN-VCH-0005',
    tripPurpose: 'Shuttle hop',
    dateRange: '2026-05-09..2026-05-09',
    category: 'transit',
    amountSyntheticCredits: 40,
    fakeAuthorizedAmount: 40,
    fakeReceiptPresent: true,
    amountMatchesAuthorization: true,
    explanation: 'Short synthetic transit hop for a quick accepted path.',
    expectedDetermination: 'accepted',
    expectedRuleIds: ['DEFAULT_ACCEPT'],
    transcript: [
      'Synthetic Traveler E',
      'Shuttle hop',
      '2026-05-09..2026-05-09',
      'transit',
      '40',
      'yes',
      'yes',
      'Short synthetic transit hop for a quick accepted path.',
    ],
  },
}

export const FIXTURE_IDS = Object.keys(FIXTURES) as FixtureRecord['id'][]
